In [1]:
#dependencies (matrix math) 
import numpy as np

In [13]:
#input data
input_data = np.array(
            [
                [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]
            ])
                
output_labels = np.array(
    [
        [0],
        [1],
        [1],
        [0]
    ])

print(input_data)
print(output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
# sigmoid function
def activate(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [4]:
# 2 weight values
synaptic_weight_0 = 2*np.random.random((3,4)) - 1
synaptic_weight_1 = 2*np.random.random((4,1)) - 1

print(synaptic_weight_0)
print(synaptic_weight_1)

[[ 0.9870709   0.73013204 -0.41240107  0.43201478]
 [ 0.84206041  0.44547436 -0.153595   -0.32906329]
 [ 0.25318732 -0.56050977  0.66340039  0.85983544]]
[[ 0.47114544]
 [-0.83945721]
 [ 0.41901016]
 [ 0.55321781]]


In [8]:
for j in range(60000):

	# Forward propagate through layers 0, 1, and 2
    layer0 = input_data
    layer1 = activate(np.dot(layer0,synaptic_weight_0))
    layer2 = activate(np.dot(layer1,synaptic_weight_1))

    #calculate error for layer 2
    layer2_error = output_labels - layer2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(layer2_error))))
        
    #Use it to compute the gradient
    layer2_gradient = layer2_error*activate(layer2,deriv=True)

    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    #Use it to compute its gradient
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    #update the weights using the gradients
    synaptic_weight_1 += layer1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer0.T.dot(layer1_gradient)


Error:0.498322385616
Error:0.00965487814204
Error:0.00653691179558
Error:0.00522996322329
Error:0.00447231578669
Error:0.00396453735153


In [12]:
#testing
print(activate(np.dot([0, 1, 1], synaptic_weight_0)))

[ 0.97525334  0.08376539  0.9817853   0.23732577]
